-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.2
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=raczora.eastus.azurecontainer.io;service_name=XEPDB1;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

SET check_function_bodies = false;





CREATE OR REPLACE PROCEDURE random_sales (p_count bigint) AS $body$
DECLARE

  v_customer_id bigint;
  v_product_id bigint;
  v_sales_id bigint;
  v_price decimal(10,2);
BEGIN
  FOR i IN 1..p_count LOOP
    -- Insert random customer
    SELECT customer_id INTO STRICT v_customer_id FROM (
      SELECT customer_id FROM Customer ORDER BY DBMS_RANDOM.RANDOM()
    ) alias1 LIMIT 1;
    INSERT INTO Sales(sales_date, customer_id) VALUES (clock_timestamp(), v_customer_id) returning sales_id INTO v_sales_id;

    -- Insert random sales items
    SELECT product_id, price INTO STRICT v_product_id, v_price FROM (
    SELECT product_id, price FROM Product ORDER BY DBMS_RANDOM.RANDOM()
    ) alias1 LIMIT 1;
    INSERT INTO SalesItems(sales_id, product_id, quantity, price)
        VALUES (v_sales_id,  v_product_id, DBMS_RANDOM.VALUE(1, 10), v_price);
  END LOOP;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE random_sales (p_count bigint) FROM PUBLIC;

