-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.2
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=raczora.eastus.azurecontainer.io;service_name=XEPDB1;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

SET check_function_bodies = false;


CREATE OR REPLACE PROCEDURE random_sales(p_count integer)
LANGUAGE plpgsql
AS $$
DECLARE 
  v_customer_id integer;
  v_product_id integer;
  v_sales_id integer;
  v_price numeric(10,2);
BEGIN
  FOR i IN 1..p_count LOOP
    -- Insert random customer
    SELECT customer_id INTO v_customer_id FROM (
      SELECT customer_id FROM Customer ORDER BY RANDOM() 
    ) c LIMIT 1;
    INSERT INTO Sales (sales_date, customer_id) VALUES (CURRENT_DATE, v_customer_id) returning sales_id INTO v_sales_id;
    
    -- Insert random sales items
    SELECT product_id, price INTO v_product_id, v_price FROM (
      SELECT product_id, price FROM Product ORDER BY RANDOM() 
    ) p LIMIT 1;
    INSERT INTO SalesItems (sales_id, product_id, quantity, price)
        VALUES (v_sales_id,  v_product_id, floor(random()*10 + 1)::integer, v_price);
  END LOOP;
END;
$$;

;
-- REVOKE ALL ON PROCEDURE random_sales (p_count bigint) FROM PUBLIC;

