ALTER SESSION set container = XEPDB1;

CREATE USER sales IDENTIFIED BY salessample;

ALTER USER sales quota unlimited on users;

GRANT CREATE SESSION, CREATE TABLE, CREATE PROCEDURE TO sales;


-- Create tables
CREATE TABLE sales.Product (
    product_id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name VARCHAR2(100) NOT NULL,
    price NUMBER(10,2) NOT NULL,
    PRIMARY KEY (product_id)
);


CREATE TABLE sales.Customer (
    customer_id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) NOT NULL,
    PRIMARY KEY (customer_id)
);

CREATE TABLE sales.Sales (
    sales_id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    customer_id NUMBER(10) NOT NULL,
    sales_date DATE NOT NULL,
    PRIMARY KEY (sales_id),
    CONSTRAINT fk_sales_customer FOREIGN KEY (customer_id) REFERENCES sales.Customer(customer_id)
);

CREATE TABLE sales.SalesItems (
    sales_id NUMBER(10) NOT NULL,
    product_id NUMBER(10) NOT NULL,
    quantity NUMBER(10) NOT NULL,
    price NUMBER(10,2) NOT NULL,
    CONSTRAINT pk_sales_items PRIMARY KEY (sales_id, product_id),
    CONSTRAINT fk_sales_items_sales FOREIGN KEY (sales_id) REFERENCES sales.Sales(sales_id),
    CONSTRAINT fk_sales_items_product FOREIGN KEY (product_id) REFERENCES sales.Product(product_id)
);





INSERT INTO sales.Product (name, price) VALUES ('Apple', 0.50);
INSERT INTO sales.Product (name, price) VALUES ('Banana', 0.25);
INSERT INTO sales.Product (name, price) VALUES ('Orange', 0.75);
INSERT INTO sales.Product (name, price) VALUES ('Pear', 0.80);
INSERT INTO sales.Product (name, price) VALUES ('Grapes', 1.50);
INSERT INTO sales.Product (name, price) VALUES ('Mango', 1.00);
INSERT INTO sales.Product (name, price) VALUES ('Pineapple', 2.00);
INSERT INTO sales.Product (name, price) VALUES ('Watermelon', 3.00);
INSERT INTO sales.Product (name, price) VALUES ('Kiwi', 0.75);
INSERT INTO sales.Product (name, price) VALUES ('Peach', 1.20);



INSERT INTO sales.Customer (name, email) VALUES ('John Smith', 'john.smith@example.com');
INSERT INTO sales.Customer (name, email) VALUES ('Jane Doe', 'jane.doe@example.com');
INSERT INTO sales.Customer (name, email) VALUES ('Bob Johnson', 'bob.johnson@example.com');
INSERT INTO sales.Customer (name, email) VALUES ('Mary Williams', 'mary.williams@example.com');
INSERT INTO sales.Customer (name, email) VALUES ('David Lee', 'david.lee@example.com');



CREATE OR REPLACE PROCEDURE sales.random_sales(p_count IN NUMBER) IS
  v_customer_id NUMBER(10);
  v_product_id NUMBER(10);
  v_sales_id NUMBER(10);
  v_price NUMBER(10,2);
BEGIN
  FOR i IN 1..p_count LOOP
    -- Insert random customer
    SELECT customer_id INTO v_customer_id FROM (
      SELECT customer_id FROM Customer ORDER BY DBMS_RANDOM.RANDOM() 
    ) WHERE ROWNUM = 1;
    INSERT INTO Sales (sales_date, customer_id) VALUES (SYSDATE, v_customer_id) returning sales_id INTO v_sales_id;
    
    -- Insert random sales items
    SELECT product_id, price INTO v_product_id, v_price FROM (
    SELECT product_id, price FROM Product ORDER BY DBMS_RANDOM.RANDOM() 
    ) WHERE ROWNUM = 1;
    INSERT INTO SalesItems (sales_id, product_id, quantity, price)
        VALUES (v_sales_id,  v_product_id, DBMS_RANDOM.VALUE(1, 10), v_price);
  END LOOP;
END random_sales;
/


